/*
 * This file is generated by jOOQ.
 */
package com.gmoon.springjooq.global.jooqschema;

import javax.annotation.processing.Generated;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import com.gmoon.springjooq.global.jooqschema.tables.TbAccessLog;
import com.gmoon.springjooq.global.jooqschema.tables.records.TbAccessLogRecord;

/**
 * A class modelling foreign key relationships and constraints of tables in
 * jooq.
 */
@Generated(
	 value = {
		  "https://www.jooq.org",
		  "jOOQ version:3.19.8",
		  "schema version:V1"
	 },
	 comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<TbAccessLogRecord> KEY_TB_ACCESS_LOG_PRIMARY = Internal.createUniqueKey(
		 TbAccessLog.TB_ACCESS_LOG, DSL.name("KEY_tb_access_log_PRIMARY"),
		 new TableField[] {TbAccessLog.TB_ACCESS_LOG.ID}, true);
}
