/*
 * This file is generated by jOOQ.
 */
package com.gmoon.batchinsert.global.jmodel.tables;


import com.gmoon.batchinsert.global.jmodel.Batchinsert;
import com.gmoon.batchinsert.global.jmodel.Keys;
import com.gmoon.batchinsert.global.jmodel.tables.TbCoupon.TbCouponPath;
import com.gmoon.batchinsert.global.jmodel.tables.records.TbCouponGroupRecord;
import org.jooq.*;
import org.jooq.Record;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import javax.annotation.processing.Generated;
import java.time.LocalDateTime;
import java.util.Collection;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.21",
        "schema version:4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbCouponGroup extends TableImpl<TbCouponGroupRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>batchinsert.tb_coupon_group</code>
     */
    public static final TbCouponGroup TB_COUPON_GROUP = new TbCouponGroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TbCouponGroupRecord> getRecordType() {
        return TbCouponGroupRecord.class;
    }

    /**
     * The column <code>batchinsert.tb_coupon_group.id</code>.
     */
    public final TableField<TbCouponGroupRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>batchinsert.tb_coupon_group.name</code>.
     */
    public final TableField<TbCouponGroupRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>batchinsert.tb_coupon_group.start_at</code>.
     */
    public final TableField<TbCouponGroupRecord, LocalDateTime> START_AT = createField(DSL.name("start_at"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>batchinsert.tb_coupon_group.end_at</code>.
     */
    public final TableField<TbCouponGroupRecord, LocalDateTime> END_AT = createField(DSL.name("end_at"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>batchinsert.tb_coupon_group.created_at</code>.
     */
    public final TableField<TbCouponGroupRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    private TbCouponGroup(Name alias, Table<TbCouponGroupRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TbCouponGroup(Name alias, Table<TbCouponGroupRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>batchinsert.tb_coupon_group</code> table
     * reference
     */
    public TbCouponGroup(String alias) {
        this(DSL.name(alias), TB_COUPON_GROUP);
    }

    /**
     * Create an aliased <code>batchinsert.tb_coupon_group</code> table
     * reference
     */
    public TbCouponGroup(Name alias) {
        this(alias, TB_COUPON_GROUP);
    }

    /**
     * Create a <code>batchinsert.tb_coupon_group</code> table reference
     */
    public TbCouponGroup() {
        this(DSL.name("tb_coupon_group"), null);
    }

    public <O extends Record> TbCouponGroup(Table<O> path, ForeignKey<O, TbCouponGroupRecord> childPath, InverseForeignKey<O, TbCouponGroupRecord> parentPath) {
        super(path, childPath, parentPath, TB_COUPON_GROUP);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.21",
            "schema version:4"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class TbCouponGroupPath extends TbCouponGroup implements Path<TbCouponGroupRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TbCouponGroupPath(Table<O> path, ForeignKey<O, TbCouponGroupRecord> childPath, InverseForeignKey<O, TbCouponGroupRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TbCouponGroupPath(Name alias, Table<TbCouponGroupRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TbCouponGroupPath as(String alias) {
            return new TbCouponGroupPath(DSL.name(alias), this);
        }

        @Override
        public TbCouponGroupPath as(Name alias) {
            return new TbCouponGroupPath(alias, this);
        }

        @Override
        public TbCouponGroupPath as(Table<?> alias) {
            return new TbCouponGroupPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Batchinsert.BATCHINSERT;
    }

    @Override
    public UniqueKey<TbCouponGroupRecord> getPrimaryKey() {
        return Keys.KEY_TB_COUPON_GROUP_PRIMARY;
    }

    private transient TbCouponPath _tbCoupon;

    /**
     * Get the implicit to-many join path to the
     * <code>batchinsert.tb_coupon</code> table
     */
    public TbCouponPath tbCoupon() {
        if (_tbCoupon == null)
            _tbCoupon = new TbCouponPath(this, null, Keys.FK_COUPON_COUPON_GROUP_ID.getInverseKey());

        return _tbCoupon;
    }

    @Override
    public TbCouponGroup as(String alias) {
        return new TbCouponGroup(DSL.name(alias), this);
    }

    @Override
    public TbCouponGroup as(Name alias) {
        return new TbCouponGroup(alias, this);
    }

    @Override
    public TbCouponGroup as(Table<?> alias) {
        return new TbCouponGroup(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TbCouponGroup rename(String name) {
        return new TbCouponGroup(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbCouponGroup rename(Name name) {
        return new TbCouponGroup(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbCouponGroup rename(Table<?> name) {
        return new TbCouponGroup(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbCouponGroup where(Condition condition) {
        return new TbCouponGroup(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbCouponGroup where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbCouponGroup where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbCouponGroup where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbCouponGroup where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbCouponGroup where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbCouponGroup where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TbCouponGroup where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbCouponGroup whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TbCouponGroup whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
