/*
 * This file is generated by jOOQ.
 */
package com.gmoon.springjooq.global.jooqschema.enums;


import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.8",
        "schema version:V1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum TbAccessLogOs implements EnumType {

    ANDROID("ANDROID"),

    CHROME("CHROME"),

    IOS("IOS"),

    LINUX("LINUX"),

    MAC("MAC"),

    MACOS("MACOS"),

    WINDOW("WINDOW");

    private final String literal;

    private TbAccessLogOs(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return null;
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static TbAccessLogOs lookupLiteral(String literal) {
        return EnumType.lookupLiteral(TbAccessLogOs.class, literal);
    }
}
