/*
 * This file is generated by jOOQ.
 */
package com.gmoon.batchinsert.global.jmodel.tables.records;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import com.gmoon.batchinsert.global.jmodel.tables.ExAccessLog;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	 value = {
		  "https://www.jooq.org",
		  "jOOQ version:3.19.8",
		  "schema version:3"
	 },
	 comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ExAccessLogRecord extends UpdatableRecordImpl<ExAccessLogRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Create a detached ExAccessLogRecord
	 */
	public ExAccessLogRecord() {
		super(ExAccessLog.EX_ACCESS_LOG);
	}

	/**
	 * Create a detached, initialised ExAccessLogRecord
	 */
	public ExAccessLogRecord(String id, String username, String ip, String os, String attemptDt) {
		super(ExAccessLog.EX_ACCESS_LOG);

		setId(id);
		setUsername(username);
		setIp(ip);
		setOs(os);
		setAttemptDt(attemptDt);
		resetChangedOnNotNull();
	}

	/**
	 * Getter for <code>batchinsert.ex_access_log.id</code>.
	 */
	public String getId() {
		return (String)get(0);
	}

	/**
	 * Setter for <code>batchinsert.ex_access_log.id</code>.
	 */
	public void setId(String value) {
		set(0, value);
	}

	/**
	 * Getter for <code>batchinsert.ex_access_log.username</code>.
	 */
	public String getUsername() {
		return (String)get(1);
	}

	/**
	 * Setter for <code>batchinsert.ex_access_log.username</code>.
	 */
	public void setUsername(String value) {
		set(1, value);
	}

	/**
	 * Getter for <code>batchinsert.ex_access_log.ip</code>.
	 */
	public String getIp() {
		return (String)get(2);
	}

	/**
	 * Setter for <code>batchinsert.ex_access_log.ip</code>.
	 */
	public void setIp(String value) {
		set(2, value);
	}

	/**
	 * Getter for <code>batchinsert.ex_access_log.os</code>.
	 */
	public String getOs() {
		return (String)get(3);
	}

	/**
	 * Setter for <code>batchinsert.ex_access_log.os</code>.
	 */
	public void setOs(String value) {
		set(3, value);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * Getter for <code>batchinsert.ex_access_log.attempt_dt</code>.
	 */
	public String getAttemptDt() {
		return (String)get(4);
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Setter for <code>batchinsert.ex_access_log.attempt_dt</code>.
	 */
	public void setAttemptDt(String value) {
		set(4, value);
	}

	@Override
	public Record1<String> key() {
		return (Record1)super.key();
	}
}
