/*
 * This file is generated by jOOQ.
 */
package com.gmoon.batchinsert.global.jmodel.tables.records;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import com.gmoon.batchinsert.global.jmodel.tables.TbAccessLog;

import jakarta.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@Generated(
	 value = {
		  "https://www.jooq.org",
		  "jOOQ version:3.14.16",
		  "schema version:3"
	 },
	 comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TbAccessLogRecord extends UpdatableRecordImpl<TbAccessLogRecord>
	 implements Record5<String, String, String, String, LocalDateTime> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>batchinsert.tb_access_log.id</code>.
	 */
	public void setId(String value) {
		set(0, value);
	}

	/**
	 * Getter for <code>batchinsert.tb_access_log.id</code>.
	 */
	public String getId() {
		return (String)get(0);
	}

	/**
	 * Setter for <code>batchinsert.tb_access_log.username</code>.
	 */
	public void setUsername(String value) {
		set(1, value);
	}

	/**
	 * Getter for <code>batchinsert.tb_access_log.username</code>.
	 */
	public String getUsername() {
		return (String)get(1);
	}

	/**
	 * Setter for <code>batchinsert.tb_access_log.ip</code>.
	 */
	public void setIp(String value) {
		set(2, value);
	}

	/**
	 * Getter for <code>batchinsert.tb_access_log.ip</code>.
	 */
	public String getIp() {
		return (String)get(2);
	}

	/**
	 * Setter for <code>batchinsert.tb_access_log.os</code>.
	 */
	public void setOs(String value) {
		set(3, value);
	}

	/**
	 * Getter for <code>batchinsert.tb_access_log.os</code>.
	 */
	public String getOs() {
		return (String)get(3);
	}

	/**
	 * Setter for <code>batchinsert.tb_access_log.attempt_dt</code>.
	 */
	public void setAttemptDt(LocalDateTime value) {
		set(4, value);
	}

	/**
	 * Getter for <code>batchinsert.tb_access_log.attempt_dt</code>.
	 */
	public LocalDateTime getAttemptDt() {
		return (LocalDateTime)get(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<String> key() {
		return (Record1)super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row5<String, String, String, String, LocalDateTime> fieldsRow() {
		return (Row5)super.fieldsRow();
	}

	@Override
	public Row5<String, String, String, String, LocalDateTime> valuesRow() {
		return (Row5)super.valuesRow();
	}

	@Override
	public Field<String> field1() {
		return TbAccessLog.TB_ACCESS_LOG.ID;
	}

	@Override
	public Field<String> field2() {
		return TbAccessLog.TB_ACCESS_LOG.USERNAME;
	}

	@Override
	public Field<String> field3() {
		return TbAccessLog.TB_ACCESS_LOG.IP;
	}

	@Override
	public Field<String> field4() {
		return TbAccessLog.TB_ACCESS_LOG.OS;
	}

	@Override
	public Field<LocalDateTime> field5() {
		return TbAccessLog.TB_ACCESS_LOG.ATTEMPT_DT;
	}

	@Override
	public String component1() {
		return getId();
	}

	@Override
	public String component2() {
		return getUsername();
	}

	@Override
	public String component3() {
		return getIp();
	}

	@Override
	public String component4() {
		return getOs();
	}

	@Override
	public LocalDateTime component5() {
		return getAttemptDt();
	}

	@Override
	public String value1() {
		return getId();
	}

	@Override
	public String value2() {
		return getUsername();
	}

	@Override
	public String value3() {
		return getIp();
	}

	@Override
	public String value4() {
		return getOs();
	}

	@Override
	public LocalDateTime value5() {
		return getAttemptDt();
	}

	@Override
	public TbAccessLogRecord value1(String value) {
		setId(value);
		return this;
	}

	@Override
	public TbAccessLogRecord value2(String value) {
		setUsername(value);
		return this;
	}

	@Override
	public TbAccessLogRecord value3(String value) {
		setIp(value);
		return this;
	}

	@Override
	public TbAccessLogRecord value4(String value) {
		setOs(value);
		return this;
	}

	@Override
	public TbAccessLogRecord value5(LocalDateTime value) {
		setAttemptDt(value);
		return this;
	}

	@Override
	public TbAccessLogRecord values(String value1, String value2, String value3, String value4, LocalDateTime value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TbAccessLogRecord
	 */
	public TbAccessLogRecord() {
		super(TbAccessLog.TB_ACCESS_LOG);
	}

	/**
	 * Create a detached, initialised TbAccessLogRecord
	 */
	public TbAccessLogRecord(String id, String username, String ip, String os, LocalDateTime attemptDt) {
		super(TbAccessLog.TB_ACCESS_LOG);

		setId(id);
		setUsername(username);
		setIp(ip);
		setOs(os);
		setAttemptDt(attemptDt);
	}
}
