/*
 * This file is generated by jOOQ.
 */
package com.gmoon.batchinsert.global.jmodel.tables.records;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import com.gmoon.batchinsert.global.jmodel.tables.TbAccessLog;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	 value = {
		  "https://www.jooq.org",
		  "jOOQ version:3.19.8",
		  "schema version:3"
	 },
	 comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TbAccessLogRecord extends UpdatableRecordImpl<TbAccessLogRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Create a detached TbAccessLogRecord
	 */
	public TbAccessLogRecord() {
		super(TbAccessLog.TB_ACCESS_LOG);
	}

	/**
	 * Create a detached, initialised TbAccessLogRecord
	 */
	public TbAccessLogRecord(String id, String username, String ip, String os, LocalDateTime attemptAt) {
		super(TbAccessLog.TB_ACCESS_LOG);

		setId(id);
		setUsername(username);
		setIp(ip);
		setOs(os);
		setAttemptAt(attemptAt);
		resetChangedOnNotNull();
	}

	/**
	 * Getter for <code>batchinsert.tb_access_log.id</code>.
	 */
	public String getId() {
		return (String)get(0);
	}

	/**
	 * Setter for <code>batchinsert.tb_access_log.id</code>.
	 */
	public void setId(String value) {
		set(0, value);
	}

	/**
	 * Getter for <code>batchinsert.tb_access_log.username</code>.
	 */
	public String getUsername() {
		return (String)get(1);
	}

	/**
	 * Setter for <code>batchinsert.tb_access_log.username</code>.
	 */
	public void setUsername(String value) {
		set(1, value);
	}

	/**
	 * Getter for <code>batchinsert.tb_access_log.ip</code>.
	 */
	public String getIp() {
		return (String)get(2);
	}

	/**
	 * Setter for <code>batchinsert.tb_access_log.ip</code>.
	 */
	public void setIp(String value) {
		set(2, value);
	}

	/**
	 * Getter for <code>batchinsert.tb_access_log.os</code>.
	 */
	public String getOs() {
		return (String)get(3);
	}

	/**
	 * Setter for <code>batchinsert.tb_access_log.os</code>.
	 */
	public void setOs(String value) {
		set(3, value);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * Getter for <code>batchinsert.tb_access_log.attempt_at</code>.
	 */
	public LocalDateTime getAttemptAt() {
		return (LocalDateTime)get(4);
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Setter for <code>batchinsert.tb_access_log.attempt_at</code>.
	 */
	public void setAttemptAt(LocalDateTime value) {
		set(4, value);
	}

	@Override
	public Record1<String> key() {
		return (Record1)super.key();
	}
}
