/*
 * This file is generated by jOOQ.
 */
package com.gmoon.batchinsert.global.jmodel.tables.records;


import com.gmoon.batchinsert.global.jmodel.tables.TbCoupon;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.21",
        "schema version:4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbCouponRecord extends UpdatableRecordImpl<TbCouponRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>batchinsert.tb_coupon.no</code>.
     */
    public void setNo(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>batchinsert.tb_coupon.no</code>.
     */
    public String getNo() {
        return (String) get(0);
    }

    /**
     * Setter for <code>batchinsert.tb_coupon.coupon_group_id</code>.
     */
    public void setCouponGroupId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>batchinsert.tb_coupon.coupon_group_id</code>.
     */
    public String getCouponGroupId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>batchinsert.tb_coupon.start_at</code>.
     */
    public void setStartAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>batchinsert.tb_coupon.start_at</code>.
     */
    public LocalDateTime getStartAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>batchinsert.tb_coupon.end_at</code>.
     */
    public void setEndAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>batchinsert.tb_coupon.end_at</code>.
     */
    public LocalDateTime getEndAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>batchinsert.tb_coupon.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>batchinsert.tb_coupon.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbCouponRecord
     */
    public TbCouponRecord() {
        super(TbCoupon.TB_COUPON);
    }

    /**
     * Create a detached, initialised TbCouponRecord
     */
    public TbCouponRecord(String no, String couponGroupId, LocalDateTime startAt, LocalDateTime endAt, LocalDateTime createdAt) {
        super(TbCoupon.TB_COUPON);

        setNo(no);
        setCouponGroupId(couponGroupId);
        setStartAt(startAt);
        setEndAt(endAt);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
