/*
 * This file is generated by jOOQ.
 */
package com.gmoon.batchinsert.global.jmodel.tables.records;


import com.gmoon.batchinsert.global.jmodel.tables.TbCouponGroup;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.21",
        "schema version:4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbCouponGroupRecord extends UpdatableRecordImpl<TbCouponGroupRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>batchinsert.tb_coupon_group.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>batchinsert.tb_coupon_group.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>batchinsert.tb_coupon_group.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>batchinsert.tb_coupon_group.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>batchinsert.tb_coupon_group.start_at</code>.
     */
    public void setStartAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>batchinsert.tb_coupon_group.start_at</code>.
     */
    public LocalDateTime getStartAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>batchinsert.tb_coupon_group.end_at</code>.
     */
    public void setEndAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>batchinsert.tb_coupon_group.end_at</code>.
     */
    public LocalDateTime getEndAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>batchinsert.tb_coupon_group.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>batchinsert.tb_coupon_group.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbCouponGroupRecord
     */
    public TbCouponGroupRecord() {
        super(TbCouponGroup.TB_COUPON_GROUP);
    }

    /**
     * Create a detached, initialised TbCouponGroupRecord
     */
    public TbCouponGroupRecord(String id, String name, LocalDateTime startAt, LocalDateTime endAt, LocalDateTime createdAt) {
        super(TbCouponGroup.TB_COUPON_GROUP);

        setId(id);
        setName(name);
        setStartAt(startAt);
        setEndAt(endAt);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
