group = "com.gmoon.spring-cache.cache-invalidation-strategy.ttl-only"
description = "ttl-only"

dependencies {
    implementation project(":spring-cache:cache-invalidation-strategy:cache-invalidation-core")
    implementation("org.springframework.boot:spring-boot-starter-web")

    compileOnly("org.projectlombok:lombok")
    annotationProcessor("org.projectlombok:lombok")

    testImplementation(testFixtures(project(":spring-cache:cache-invalidation-strategy:cache-invalidation-core")))
    testCompileOnly("org.projectlombok:lombok")
    testAnnotationProcessor("org.projectlombok:lombok")
}
