/*
 * This file is generated by jOOQ.
 */
package com.gmoon.springjooq.global.jooqschema.tables.records;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import com.gmoon.springjooq.global.jooqschema.enums.TbAccessLogOs;
import com.gmoon.springjooq.global.jooqschema.tables.TbAccessLog;

/**
 * This class is generated by jOOQ.
 */
@Generated(
	 value = {
		  "https://www.jooq.org",
		  "jOOQ version:3.19.8",
		  "schema version:V1"
	 },
	 comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TbAccessLogRecord extends UpdatableRecordImpl<TbAccessLogRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>PUBLIC.TB_ACCESS_LOG.ATTEMPT_DT</code>.
	 */
	public void setAttemptDt(LocalDateTime value) {
		set(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.TB_ACCESS_LOG.ATTEMPT_DT</code>.
	 */
	public LocalDateTime getAttemptDt() {
		return (LocalDateTime)get(0);
	}

	/**
	 * Setter for <code>PUBLIC.TB_ACCESS_LOG.ID</code>.
	 */
	public void setId(String value) {
		set(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.TB_ACCESS_LOG.ID</code>.
	 */
	public String getId() {
		return (String)get(1);
	}

	/**
	 * Setter for <code>PUBLIC.TB_ACCESS_LOG.USERNAME</code>.
	 */
	public void setUsername(String value) {
		set(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.TB_ACCESS_LOG.USERNAME</code>.
	 */
	public String getUsername() {
		return (String)get(2);
	}

	/**
	 * Setter for <code>PUBLIC.TB_ACCESS_LOG.IP</code>.
	 */
	public void setIp(String value) {
		set(3, value);
	}

	/**
	 * Getter for <code>PUBLIC.TB_ACCESS_LOG.IP</code>.
	 */
	public String getIp() {
		return (String)get(3);
	}

	/**
	 * Setter for <code>PUBLIC.TB_ACCESS_LOG.OS</code>.
	 */
	public void setOs(TbAccessLogOs value) {
		set(4, value);
	}

	/**
	 * Getter for <code>PUBLIC.TB_ACCESS_LOG.OS</code>.
	 */
	public TbAccessLogOs getOs() {
		return (TbAccessLogOs)get(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<String> key() {
		return (Record1)super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TbAccessLogRecord
	 */
	public TbAccessLogRecord() {
		super(TbAccessLog.TB_ACCESS_LOG);
	}

	/**
	 * Create a detached, initialised TbAccessLogRecord
	 */
	public TbAccessLogRecord(LocalDateTime attemptDt, String id, String username, String ip, TbAccessLogOs os) {
		super(TbAccessLog.TB_ACCESS_LOG);

		setAttemptDt(attemptDt);
		setId(id);
		setUsername(username);
		setIp(ip);
		setOs(os);
		resetChangedOnNotNull();
	}
}
