spring:
  application:
    name: querydsl-sql

  datasource:
    driver-class-name: @jdbc.driver@
    url: @jdbc.url@?@jdbc.option@
    username: @jdbc.username@
    password: @jdbc.password@
    hikari:
      driver-class-name: @jdbc.driver@

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: &showsql true
    generate-ddl: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        #        "[hbm2ddl.auto]": validate
        #        format_sql: *showsql
        # batch
        order_inserts: true
        order_updates: true
        "[jdbc.batch_size]": 500
