/*
 * This file is generated by jOOQ.
 */
package com.gmoon.batchinsert.global.jmodel;

import javax.annotation.Generated;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import com.gmoon.batchinsert.global.jmodel.tables.FlywaySchemaHistory;
import com.gmoon.batchinsert.global.jmodel.tables.TbAccessLog;
import com.gmoon.batchinsert.global.jmodel.tables.records.FlywaySchemaHistoryRecord;
import com.gmoon.batchinsert.global.jmodel.tables.records.TbAccessLogRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * batchinsert.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.16",
        "catalog version:2",
        "schema version:2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FlywaySchemaHistoryRecord> KEY_FLYWAY_SCHEMA_HISTORY_PRIMARY = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("KEY_flyway_schema_history_PRIMARY"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<TbAccessLogRecord> KEY_TB_ACCESS_LOG_PRIMARY = Internal.createUniqueKey(TbAccessLog.TB_ACCESS_LOG, DSL.name("KEY_tb_access_log_PRIMARY"), new TableField[] { TbAccessLog.TB_ACCESS_LOG.ID }, true);
}
