spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hibernate_annotation?createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false&characterEncoding=UTF-8
    username: root
    password: 111111

  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: &show-sql true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.MySQLDialect
        "[jdbc.time_zone]": UTC
  #        "[hbm2ddl.auto]": create-drop
#        show-sql: *show-sql
#        format_sql: *show-sql
#        highlight_sql: *show-sql
#        use_sql_comments: *show-sql

  sql:
    init:
      mode: always
      encoding: UTF-8
      platform: mysql
#      schema-locations: classpath*:db/schema.sql
      data-locations: classpath*:db/data.sql
      continue-on-error: true

logging:
  level:
    "[org.hibernate.type.descriptor.sql]": OFF
