spring:
  application:
    name: querydsl-sql-core

  datasource:
    driver-class-name: @jdbc.driver@
    url: @jdbc.url@/@db.schema@?@jdbc.option@
    username: @jdbc.username@
    password: @jdbc.password@
    hikari:
      driver-class-name: @jdbc.driver@

  jpa:
    open-in-view: false
    database-platform: @hibernate.dialect@
    show-sql: &showsql true
    generate-ddl: true
    hibernate:
      ddl-auto: create

    properties:
      # application \uC2E4\uD589 \uC2DC DDL \uD30C\uC77C\uB9CC export \uAC00\uB2A5 (DB\uC5D0\uB294 \uC801\uC6A9\uB418\uC9C0 \uC54A\uC74C).
      #      javax.persistence.schema-generation.scripts.action: create
      #      javax.persistence.schema-generation.scripts.create-target: schema.sql

      hibernate:
        "[hbm2ddl.auto]": create
        #        format_sql: *showsql
        # batch
        "[jdbc.batch_size]": 500
        order_inserts: true
        order_updates: true
