logging:
  level:
    "[org.hibernate.type.descriptor.sql]": trace

spring:
  jpa:
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        "[hbm2ddl.auto]": create-drop
        show-sql: true
        format_sql: true
        use_sql_comments: true
