spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springlock?createDatabaseIfNotExist=true&logger=Slf4JLogger&profileSQL=true&maxQuerySizeToLog=999999&characterEncoding=UTF-8
    username: root
    password: 111111

  test:
    database:
      replace: none

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MariaDBDialect
#    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    show-sql: &show-sql true
    hibernate:
      ddl-auto: create-drop
    properties:
#      "[javax.persistence.query.timeout]": 1000
      "[jakarta.persistence.query.timeout]": 1000
      hibernate:
#        "[hbm2ddl.auto]": create-drop
        #      "[hbm2ddl.auto]": create-drop
#        globally_quoted_identifiers: true
#        show_sql: *show-sql
        #        use_sql_comments: *show-sql
        #        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  sql:
    init:
      mode: always
      continue-on-error: true
