spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springlock?createDatabaseIfNotExist=true&logger=Slf4JLogger&profileSQL=true&maxQuerySizeToLog=999999
    username: root
    password: 111111
  test:
    database:
      replace: none
  jpa:
    show-sql: &show-sql true
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MariaDB10Dialect
    hibernate:
      ddl-auto: create
#      ddl-auto: create-drop
    properties:
      ['javax.persistence.query.timeout']: 1000
      hibernate:
        show_sql: *show-sql
        #        use_sql_comments: *show-sql
        #        format_sql: true
        globally_quoted_identifiers: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

#"[logging.level.org.hibernate.type.descriptor.sql]": trace
