/*
 * This file is generated by jOOQ.
 */
package com.gmoon.springjooq.global.jooqschema;

import javax.annotation.Generated;

import com.gmoon.springjooq.global.jooqschema.tables.TbAccessLog;


/**
 * Convenience access to all tables in PUBLIC.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.16",
        "schema version:V1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.TB_ACCESS_LOG</code>.
     */
    public static final TbAccessLog TB_ACCESS_LOG = TbAccessLog.TB_ACCESS_LOG;
}
