spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        show-sql: true
        format_sql: false
        use_sql_comments: false
        ddl-auto: create-drop

logging:
  level:
    "[org.hibernate.type.descriptor.sql]": trace
    "[org.quickperf.*]": INFO

