spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        "[hbm2ddl.auto]": create-drop
        show-sql: true
        format_sql: false
        use_sql_comments: false

logging:
  level:
    "[org.hibernate.type.descriptor.sql]": trace
    "[org.quickperf.*]": INFO

