spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/hibernate-envers?createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false&characterEncoding=UTF-8
      username: root
      password: 111111

  jpa:
    open-in-view: false
    show-sql: &show-sql true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      "[org.hibernate.envers.audit_table_suffix]": _h
      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
        "[hbm2ddl.auto]": create-drop
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
        audit_table_suffix: _h

logging:
  level:
    "[com.gmoon]": TRACE
    "[org.hibernate.type.descriptor.sql]": OFF
