spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl_auto: create-drop
        audit_table_suffix: _h
      org:
        hibernate:
          envers:
            audit_table_suffix: _h
logging:
  level:
    "[com.gmoon]": trace
    "[org.hibernate.type.descriptor.sql]": trace
