spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/hibernate_envers?createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false&characterEncoding=UTF-8
      username: root
      password: 111111

  jpa:
    open-in-view: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: &show-sql true
    hibernate:
      ddl-auto: create
    properties:
      "[org.hibernate.envers.audit_table_suffix]": _h
      hibernate:
        globally_quoted_identifiers: true
        auto_quote_keyword: true
#        dialect: org.hibernate.dialect.MySQLDialect
#        "[hbm2ddl.auto]": create-drop
#        show_sql: true
        format_sql: *show-sql
        highlight_sql: *show-sql
#        use_sql_comments: *show-sql


logging:
  level:
    "[com.gmoon]": TRACE
    "[org.hibernate.sql]": DEBUG
    "[org.hibernate.type.descriptor.sql]": TRACE
