spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/hibernate-envers?createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false&characterEncoding=UTF-8
      username: root
      password: 111111

  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      "[org.hibernate.envers.audit_table_suffix]": _h
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        "[hbm2ddl.auto]": create-drop
        show_sql: true
        #        format_sql: true
        use_sql_comments: true
        audit_table_suffix: _h

logging:
  level:
    "[com.gmoon]": trace
    "[org.hibernate.type.descriptor.sql]": trace
