spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password:
  jpa:
    show-sql: true

    properties:
      "[org.hibernate.envers.audit_table_suffix]": _h
      hibernate:
        "[hbm2ddl.auto]": create-drop
        #        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        audit_table_suffix: _h
logging:
  level:
    "[com.gmoon]": trace
    "[org.hibernate.type.descriptor.sql]": trace
