spring:
  application:
    name: commons-apache-poi

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_poi?createDatabaseIfNotExist=true&serverTimezone=UTC&characterEncoding=UTF-8&logger=Slf4JLogger&profileSQL=true&maxQuerySizeToLog=999999
    #    url: jdbc:mysql://localhost:3306/spring_poi?createDatabaseIfNotExist=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 111111

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    #    HHH90000025: MySQLDialect does not need to be specified explicitly using 'hibernate.dialect' (remove the property setting and it will be selected by default)
    #    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.MySQLDialect
        #        use_sql_comments: true
        #        format_sql: true
        show_sql: true
        highlight_sql: true

service:
  validation:
    regex:
      username: "^[0-9a-zA-Z]{4,24}$"
      email: "^[a-zA-Z0-9+._%-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"

  excel:
    upload:
      storage-path: "src/test/resources/excelupload"
      max-rows: 1_000
      chunk-size: 100

logging:
  level:
    "[com.gmoon]": TRACE
    "[com.gmoon.springpoi.common.excel.sax.handler.AbstractSaxXlsxHandler]": WARN

    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.orm.jdbc.bind]": TRACE
    #    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    MYSQL: TRACE
