api:
  version: v1

jwt:
  secret: SERET

spring:
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    show-sql: &show-sql true
    generate-ddl: true
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.H2Dialect
        "[hbm2ddl.auto]": create-drop
        "[jdbc.time_zone]": UTC
#        show-sql: *show-sql
#        format_sql: *show-sql
#        highlight_sql: *show-sql
#        use_sql_comments: *show-sql

logging:
  level:
    "[org.springframework.security]": trace
