/*
 * This file is generated by jOOQ.
 */
package com.gmoon.batchinsert.global.jmodel;


import com.gmoon.batchinsert.global.jmodel.tables.*;
import com.gmoon.batchinsert.global.jmodel.tables.records.*;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import javax.annotation.processing.Generated;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * batchinsert.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.21",
        "schema version:4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ExAccessLogRecord> KEY_EX_ACCESS_LOG_PRIMARY = Internal.createUniqueKey(ExAccessLog.EX_ACCESS_LOG, DSL.name("KEY_ex_access_log_PRIMARY"), new TableField[] { ExAccessLog.EX_ACCESS_LOG.ID }, true);
    public static final UniqueKey<FlywaySchemaHistoryRecord> KEY_FLYWAY_SCHEMA_HISTORY_PRIMARY = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("KEY_flyway_schema_history_PRIMARY"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<TbAccessLogRecord> KEY_TB_ACCESS_LOG_PRIMARY = Internal.createUniqueKey(TbAccessLog.TB_ACCESS_LOG, DSL.name("KEY_tb_access_log_PRIMARY"), new TableField[] { TbAccessLog.TB_ACCESS_LOG.ID }, true);
    public static final UniqueKey<TbCouponRecord> KEY_TB_COUPON_PRIMARY = Internal.createUniqueKey(TbCoupon.TB_COUPON, DSL.name("KEY_tb_coupon_PRIMARY"), new TableField[] { TbCoupon.TB_COUPON.NO }, true);
    public static final UniqueKey<TbCouponGroupRecord> KEY_TB_COUPON_GROUP_PRIMARY = Internal.createUniqueKey(TbCouponGroup.TB_COUPON_GROUP, DSL.name("KEY_tb_coupon_group_PRIMARY"), new TableField[] { TbCouponGroup.TB_COUPON_GROUP.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<TbCouponRecord, TbCouponGroupRecord> FK_COUPON_COUPON_GROUP_ID = Internal.createForeignKey(TbCoupon.TB_COUPON, DSL.name("fk_coupon_coupon_group_id"), new TableField[] { TbCoupon.TB_COUPON.COUPON_GROUP_ID }, Keys.KEY_TB_COUPON_GROUP_PRIMARY, new TableField[] { TbCouponGroup.TB_COUPON_GROUP.ID }, true);
}
