/*
 * This file is generated by jOOQ.
 */
package com.gmoon.batchinsert.global.jmodel;


import com.gmoon.batchinsert.global.jmodel.tables.*;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in batchinsert.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.21",
        "schema version:4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>batchinsert.ex_access_log</code>.
     */
    public static final ExAccessLog EX_ACCESS_LOG = ExAccessLog.EX_ACCESS_LOG;

    /**
     * The table <code>batchinsert.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>batchinsert.tb_access_log</code>.
     */
    public static final TbAccessLog TB_ACCESS_LOG = TbAccessLog.TB_ACCESS_LOG;

    /**
     * The table <code>batchinsert.tb_coupon</code>.
     */
    public static final TbCoupon TB_COUPON = TbCoupon.TB_COUPON;

    /**
     * The table <code>batchinsert.tb_coupon_group</code>.
     */
    public static final TbCouponGroup TB_COUPON_GROUP = TbCouponGroup.TB_COUPON_GROUP;
}
