/*
 * This file is generated by jOOQ.
 */
package com.gmoon.batchinsert.global.jmodel;

import javax.annotation.Generated;

import com.gmoon.batchinsert.global.jmodel.tables.ExAccessLog;
import com.gmoon.batchinsert.global.jmodel.tables.FlywaySchemaHistory;
import com.gmoon.batchinsert.global.jmodel.tables.TbAccessLog;

/**
 * Convenience access to all tables in batchinsert.
 */
@Generated(
	 value = {
		  "https://www.jooq.org",
		  "jOOQ version:3.14.16",
		  "schema version:3"
	 },
	 comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

	/**
	 * The table <code>batchinsert.ex_access_log</code>.
	 */
	public static final ExAccessLog EX_ACCESS_LOG = ExAccessLog.EX_ACCESS_LOG;

	/**
	 * The table <code>batchinsert.flyway_schema_history</code>.
	 */
	public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

	/**
	 * The table <code>batchinsert.tb_access_log</code>.
	 */
	public static final TbAccessLog TB_ACCESS_LOG = TbAccessLog.TB_ACCESS_LOG;
}
