spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quartz?createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false&characterEncoding=UTF-8
    username: root
    password: 111111
    hikari:
      pool-name: gmoon-pool

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
#      autoconfigure.orm.jpa.HibernateJpaConfiguration default naming strategy
#      naming:
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: &show-sql true
    properties:
      hibernate:
        "[hbm2ddl.auto]": update
        "[id.new_generator_mappings]": false
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#        show-sql: *show-sql
#        format_sql: *show-sql
#        highlight_sql: *show-sql
#        use_sql_comments: *show-sql
        "[jdbc.time_zone]": UTC

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    # http://www.quartz-scheduler.org/documentation/2.4.0-SNAPSHOT/configuration.html#configuration-of-database-clustering-achieve-fail-over-and-load-balancing-with-jdbc-jobstore
    properties:
      ###########################
      # main scheduler
      ###########################
#      "[org.quartz.scheduler.instanceName]": NON_CLUSTERED
      "[org.quartz.scheduler.instanceId]": AUTO
      "[org.quartz.scheduler.instanceIdGenerator.class]": com.gmoon.springquartzcluster.quartz.core.CustomInstanceIdGenerator
      ###########################
      # thread pool
      ###########################
#      "[org.quartz.threadPool.class]": org.quartz.simpl.SimpleThreadPool
      "[org.quartz.threadPool.threadCount]": 20
      "[org.quartz.threadPool.threadPriority]": 5
      "[org.quartz.threadPool.threadNamePrefix]": gmoon-quartz-pool
      ###########################
      # job-store
      ###########################
#      "[org.quartz.jobStore.class]": org.quartz.impl.jdbcjobstore.JobStoreTX
#      "[org.quartz.jobStore.driverDelegateClass]": org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      "[org.quartz.jobStore.tablePrefix]": QUARTZ_
      "[org.quartz.jobStore.useProperties]": true
#      "[org.quartz.jobStore.misfireThreshold]": 60000
      "[org.quartz.jobStore.isClustered]": true
      "[org.quartz.jobStore.clusterCheckinInterval]": 20000

logging:
  level:
    "[org.hibernate.type.descriptor.sql]": OFF
