spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hibernate-type?createDatabaseIfNotExist=true&logger=Slf4JLogger&profileSQL=true&maxQuerySizeToLog=999999
    username: root
    password: 111111

  jpa:
    open-in-view: false
    show-sql: &show-sql true
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        ddl-auto: create-drop
        "[id.new_generator_mappings]": false
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: *show-sql
        format_sql: *show-sql
        use_sql_comments: *show-sql
        "[jdbc.time_zone]": UTC

  sql:
    init:
      mode: always
      continue-on-error: true

logging:
  level:
    "[org.hibernate.type.descriptor.sql]": trace
