spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hibernate-type?createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false&characterEncoding=UTF-8
    username: root
    password: 111111
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    show-sql: &show-sql true
    database-platform: org.hibernate.dialect.MariaDB10Dialect
    hibernate:
      ddl-auto: create-drop
      properties:
        hibernate:
          "[id.new_generator_mappings]": false
          physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          show-sql: *show-sql
          format_sql: *show-sql
          use_sql_comments: *show-sql
          "[jdbc.time_zone]": UTC
logging:
  level:
    "[org.hibernate.type.descriptor.sql]": trace
