services:
  mariadb:
    image: mariadb:10.3
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=111111
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --collation-server=utf8_unicode_ci
