spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        globally_quoted_identifiers: true
    defer-datasource-initialization: true

logging:
  level:
    "[org.hibernate.type.descriptor.sql]": trace

