spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password:
  jpa:
    show-sql: &show-sql true
    properties:
      hibernate:
#        show_sql: *show-sql
#        format_sql: *show-sql
#        highlight_sql: *show-sql
#        use_sql_comments: *show-sql
        globally_quoted_identifiers: true
    defer-datasource-initialization: true

logging:
  level:
    "[org.hibernate.type.descriptor.sql]": OFF

