service:
  db-schema: dbrecovery

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/${service.db-schema}?createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false&characterEncoding=UTF-8&logger=Slf4JLogger&profileSQL=true&maxQuerySizeToLog=999999
    url: jdbc:mysql://localhost:3306/${service.db-schema}?createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false&characterEncoding=UTF-8
    username: root
    password: 111111

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: &show-sql true
    properties:
      hibernate:
        "[hbm2ddl.auto]": create

  sql:
    init:
      mode: always
      encoding: UTF-8
      data-locations: classpath*:data.sql
      continue-on-error: false

logging:
  level:
    "[MySQL]": DEBUG
    "[com.gmoon]": DEBUG
