plugins {
    id "java-library"
}

group = "com.gmoon.spring-cache.cache-invalidation-strategy.cache-invalidation-core"
description = "cache-invalidation-core"

bootJar {
    enabled = false
}

jar {
    enabled = true
}

dependencies {
    api("org.springframework.boot:spring-boot-starter-data-jpa")
    api("org.springframework.boot:spring-boot-starter-data-redis")
    api("org.springframework.boot:spring-boot-starter-cache")
    api("org.springframework.boot:spring-boot-starter-json")

    compileOnly("org.projectlombok:lombok")
    annotationProcessor("org.projectlombok:lombok")

    runtimeOnly(libs.jdbc.mysql)

    testImplementation("org.springframework.boot:spring-boot-starter-test")
}
