spring:
  data:
    redis:
  #    jedis, lettuce
      client-type: lettuce
      client-name: gmoon-redis-client
      connect-timeout: 10
      host: localhost
      port: 6379

  #    jedis:
  #      pool:
  #        enabled: true

      # STANDALONE, SENTINEL, ELASTI_CACHE
      server-type: STANDALONE

      # Redis Cluster
      cluster:
        nodes:
          - 127.0.0.1:6380
          - 127.0.0.1:6381
        max-redirects: 3

      # Redis Sentinel
      sentinel:
        master: gmoon-master
        nodes:
          - 127.0.0.1:26379 # default port
          - 127.0.0.1:26380
          - 127.0.0.1:26381

  # JPA persistence
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    show-sql: &show-sql true
    properties:
      hibernate:
        "[hbm2ddl.auto]": update
        globally_quoted_identifiers: true
        #          dialect: org.hibernate.dialect.H2Dialect
#        show-sql: *show-sql
#        format_sql: *show-sql
#        use_sql_comments: *show-sql
        "[jdbc.time_zone]": UTC

  # https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.data-initialization
  sql:
    init:
      mode: always
      encoding: UTF-8
      platform: h2
      schema-locations: classpath*:db/schema-${spring.sql.init.platform}.sql
      data-locations: classpath*:db/data-${spring.sql.init.platform}.sql
      continue-on-error: false
