package com.gmoon.dbrecovery.global.persistence.datasource;

import java.sql.PreparedStatement;
import java.sql.SQLException;

interface RedefineConnection {

	PreparedStatement prepareStatement(String sql) throws SQLException;

	PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException;

	PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException;

	PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException;

	PreparedStatement prepareStatement(String sql, int columnIndexes[]) throws SQLException;

	PreparedStatement prepareStatement(String sql, String columnNames[]) throws SQLException;

}
