spring:
  r2dbc:
#    https://r2dbc.io/spec/0.8.3.RELEASE/spec/html/#overview.connection.url
    url: r2dbc:mariadb://localhost:3306/spring-data-r2dbc?serverTimezone=UTC&useLegacyDatetimeCode=false&characterEncoding=UTF-8
    username: root
    password: 111111
    pool:
      validation-query: SELECT 1

logging:
  level:
    "[org.springframework.transaction]": TRACE
    "[org.springframework.data.r2dbc.connectionfactory]": TRACE
