spring:
  application:
    name: spring-kafka-consumer

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_kafka?createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false&characterEncoding=UTF-8&logger=Slf4JLogger&profileSQL=true&maxQuerySizeToLog=999999
    username: root
    password: 111111
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
