spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-jpa-pagination?createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false&characterEncoding=UTF-8&logger=Slf4JLogger&profileSQL=true&maxQuerySizeToLog=999999
    username: root
    password: 111111

  # JPA Persistence
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: false
    show-sql: &show-sql true
    properties:
      hibernate:
        "[hbm2ddl.auto]": none
        "[jdbc.time_zone]": UTC
#        show-sql: &show-sql true
#        format_sql: *show-sql
#        highlight_sql: *show-sql
#        use_sql_comments: *show-sql

  # Sql
  # https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.data-initialization
  sql:
    init:
      mode: always
      continue-on-error: false
      encoding: UTF-8
      platform: mysql

#      schema-locations: classpath*:db/schema-${spring.sql.init.platform}.sql
#      data-locations: classpath*:db/data-${spring.sql.init.platform}.sql

logging:
  level:
    "[MYSQL]": OFF
    "[org.hibernate.SQL]": trace
    "[org.hibernate.type.descriptor.sql]": trace
