spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:~/test
      driver-class-name: org.h2.Driver
      username: sa
      password:
  jpa:
    hibernate:
      ddl-auto: create-drop
#    show-sql: true

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl_auto: create-drop
        dialect: org.hibernate.dialect.H2Dialect
        audit_table_suffix: _h
      org:
        hibernate:
          envers:
            audit_table_suffix: _h
logging:
  level:
    com:
      gmoon: trace
    org:
      hibernate:
        type:
          descriptor:
            sql: trace