spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
#    show-sql: true

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
      org:
        hibernate:
          envers:
            audit_table_suffix: _h
logging:
  level:
    com:
      gmoon: trace
    org:
      hibernate:
        type:
          descriptor:
            sql: trace