server:
  port: 9000
  address: 0.0.0.0

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: &show-sql true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show-sql: *show-sql
        format_sql: *show-sql
        use_sql_comments: *show-sql
        jdbc:
          time_zone: UTC
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      encoding: UTF-8

logging:
  level:
    "[org.hibernate.type.descriptor.sql]": trace
