api:
  version: v2
jwt:
  secret: SECRET

server:
  port: 9000
  address: 0.0.0.0

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cors?createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false&characterEncoding=UTF-8&logger=Slf4JLogger&profileSQL=true&maxQuerySizeToLog=999999
    username: root
    password: 111111

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: &show-sql true
    properties:
      hibernate:
        "[hbm2ddl.auto]": update
#        dialect: org.hibernate.dialect.MySQLDialect
#        show-sql: *show-sql
#        format_sql: *show-sql
#        use_sql_comments: *show-sql
        globally_quoted_identifiers: true
        "[jdbc.time_zone]": UTC

# https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.data-initialization
  sql:
    init:
      mode: always
      encoding: UTF-8
      platform: mysql
      schema-locations: classpath*:db/schema-${spring.sql.init.platform}.sql
      data-locations: classpath*:db/data-${spring.sql.init.platform}.sql
      continue-on-error: false

logging:
  level:
    "[org.hibernate.type.descriptor.sql]": trace
