spring:
  application:
    name: spring-kafka-producer

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/spring_kafka?createDatabaseIfNotExist=true&logger=Slf4JLogger&profileSQL=true&maxQuerySizeToLog=999999
    url: jdbc:mysql://localhost:3306/spring_kafka?createDatabaseIfNotExist=true
    username: root
    password: 111111

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true

    properties:
      hibernate:
        globally_quoted_identifiers: true
        auto_quote_keyword: true

