##### spring hikariCP datasource config
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost:9092/~/testdb
      driver-class-name: org.h2.Driver
      username: sa
      password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
#        format_sql: true
        format_sql: false
        use_sql_comments: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    com:
      gmoon: trace
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
  config: src/main/resources/log4j2.xml