spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
#        use_sql_comments: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    com:
      gmoon: trace
    org:
      hibernate:
        type:
          descriptor:
            sql: trace