# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
# https://docs.github.com/ko/actions/using-workflows
name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      #      mariadb:
      #        image: mariadb:10.3
      #        env:
      #          MYSQL_USER: root
      #          MYSQL_ROOT_PASSWORD: 111111
      #        ports:
      #          - 3306:3306
      #        options: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --collation-server=utf8_unicode_ci

      # Label used to access the service container
      # https://docs.github.com/en/actions/using-containerized-services/creating-redis-service-containers
      redis:
        # Docker Hub image
        image: redis
        ports:
          - 6379:6379
      rabbitmq:
        image: rabbitmq
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672

    # https://github.com/marketplace
    # https://github.com/marketplace/actions/start-mariadb
    # https://github.com/marketplace/actions/actions-setup-mysql
    steps:
      - name: Set up mysql
        uses: shogo82148/actions-setup-mysql@v1
#        uses: getong/mariadb-action@v1.11
        with:
          mysql-version: "8.0"
          host port: 3306 # Optional, default value is 3306. The port of host
          container port: 3306 # Optional, default value is 3306. The port of container
          character set server: 'utf8mb4' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          collation server: 'utf8mb4_unicode_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          mariadb version: '11.2.4-jammy' # Optional, default value is "latest". The version of the MariaDB
          #          mariadb version: '10.4.10' # Optional, default value is "latest". The version of the MariaDB
          #          mysql database: 'some_test' # Optional, default value is "test". The specified database which will be create
          mysql root password: 111111 # Required if "mysql user" is empty, default is empty. The root superuser password
      #          mysql user: 'developer' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
      #          mysql password: ${{ secrets.DatabasePassword }} # Required if "mysql user" exists. The password for the "mysql user"
      - run: mysql -uroot -e 'SELECT version()'

      - name: checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Test with Maven
        run: mvn -B test --file pom.xml
